id: P007964
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG5151
  title: བསྟན་བཅོས་ཟབ་མོ་ནང་དོན་གྱི་གཏོང་ཐུན་རབ་གསལ་ཉི་མའི་སྙིང་པོ་
  author: ''
  volumes:
    56f63217924143db802eb6bd60f8a2a3:
      image_group_id: I1KG5168
      title: Volume 1 of bstan bcos zab mo nang don gyi gtong thun rab gsal nyi ma'i
        snying po
      volume_number: 1
      total_pages: 222
      base_file: v001.txt
