id: P007964
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5151
  title: བསྟན་བཅོས་ཟབ་མོ་ནང་དོན་གྱི་གཏོང་ཐུན་རབ་གསལ་ཉི་མའི་སྙིང་པོ་
  author: ''
  volumes:
    c8161ecabf7e4bd1ac6f663102032873:
      image_group_id: I1KG5168
      title: ''
      volume_number: 1
      total_pages: 222
ebook_metadata:
  title: བསྟན་བཅོས་ཟབ་མོ་ནང་དོན་གྱི་གཏོང་ཐུན་རབ་གསལ་ཉི་མའི་སྙིང་པོ་
  author: ''
  sku: P007964
  cover: cover.jpg
  layers:
  - pagination
