id: I25B35252
legacy_id: P007964
ocr_import_info:
  bdrc_scan_id: W1KG5151
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T02:29:32'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T17:11:25.033343+00:00'
last_modified: 2022-09-01 01:11:33.663597
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG5151
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG5151
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསྟན་བཅོས་ཟབ་མོ་ནང་དོན་གྱི་གཏོང་ཐུན་རབ་གསལ་ཉི་མའི་སྙིང་པོ།
  author: ཞྭ་དམར ༠༥་དཀོན་མཆོག་ཡན་ལག
statistics:
  ocr_word_mean_confidence_index: 0.7704916407790227
  ocr_word_median_confidence_index: 0.8700000047683716
quality: null
bases:
  I1KG5168:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5168
      total_pages: 222
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5168.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7704916407790227
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
