id: I25B35252
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T02:31:02+00:00'
last_modified: '2022-06-09T08:04:21.423906+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5151
  title: བསྟན་བཅོས་ཟབ་མོ་ནང་དོན་གྱི་གཏོང་ཐུན་རབ་གསལ་ཉི་མའི་སྙིང་པོ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C0AC:
      image_group_id: I1KG5168
      title: Volume 1 of bstan bcos zab mo nang don gyi gtong thun rab gsal nyi ma'i
        snying po
      total_pages: 222
      order: 1
      base_file: C0AC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
